//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment_asp.net.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class assignmentEntities : DbContext
    {
        public assignmentEntities()
            : base("name=assignmentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<country> countries { get; set; }
        public virtual DbSet<state1> state1 { get; set; }
        public virtual DbSet<state2> state2 { get; set; }
        public virtual DbSet<state3> state3 { get; set; }
        public virtual DbSet<state4> state4 { get; set; }
        public virtual DbSet<state> states { get; set; }
    }
}
